# Generated by Django 4.2.4 on 2023-08-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='respondant',
            name='occupation',
            field=models.CharField(choices=[('STU', 'Student'), ('EMP', 'Employee'), ('FAM', 'Farmer'), ('MER', 'Business person'), ('UNE', 'Unemploy')], default='STU', max_length=3),
        ),
    ]
